In [ ]:
import pandas as pd

In [ ]:
# tsv_file='encoding.tsv'
  
# # readinag given tsv file
# csv_table=pd.read_table(tsv_file,sep='\t')
  
# # converting tsv file into csv
# csv_table.to_csv('encoding.csv',index=False)

In [ ]:
# df = pd.read_csv('encoding.csv')

In [ ]:
# df.head()

In [ ]:
# df.shape

(4287, 40)

In [ ]:
header_list = ["D1", "Sequence"]

data=pd.read_csv('/content/drive/MyDrive/Project/astral-scopedom-seqres-gd-sel-gs-bib-40-2.07.fa.txt',sep='$', names=header_list,header=None)
data.head()

,D1,Sequence
0,>d1dlwa_ a.1.1.1 (A:) Protozoan/bacterial hemo...,slfeqlggqaavqavtaqfyaniqadatvatffngidmpnqtnkta...
1,>d2gkma_ a.1.1.1 (A:) Protozoan/bacterial hemo...,gllsrlrkrepisiydkiggheaievvvedffvrvladdqlsaffs...
2,>d1ngka_ a.1.1.1 (A:) Protozoan/bacterial hemo...,ksfydavggaktfdaivsrfyaqvaedevlrrvypeddlagaeerl...
3,>d2bkma_ a.1.1.1 (A:) automated matches {Geoba...,eqwqtlyeaiggeetvaklveafyrrvaahpdlrpifpddltetah...
4,>d4i0va_ a.1.1.1 (A:) automated matches {Synec...,aslyeklggaaavdlavekfygkvladervnrffvntdmakqkqhq...

In [ ]:
data.tail()

,D1,Sequence
14318,>d3s2ra_ g.97.1.0 (A:) automated matches {Thal...,ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...
14319,>d4c3hd_ g.98.1.1 (D:) RNA polymerase I subuni...,sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...
14320,>d3jb9e_ g.99.1.1 (e:) Pre-mRNA splicing facto...,rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...
14321,>d5lj3n2 g.100.1.1 (N:6-144) Pre-mRNA splicing...,nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...
14322,>d5syba_ g.101.1.1 (A:) Pre-mRNA splicing fact...,akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...

In [ ]:
data.describe()

,D1,Sequence
count,14323,14323
unique,14323,14323
top,>d1dlwa_ a.1.1.1 (A:) Protozoan/bacterial hemo...,slfeqlggqaavqavtaqfyaniqadatvatffngidmpnqtnkta...
freq,1,1

In [ ]:
data[['d1','d2']]=data['D1'].str.split('(', n=1, expand=True) 
data[['d1','class','t']]=data['d1'].str.split('_ | ', expand=True)  
data[['d3','d2']]= data['d2'].str.split(':', n=1,expand=True)

In [ ]:
data.shape

(14323, 7)

In [ ]:
data[['d2','TaxId','t','t']]=data['d2'].str.split(': |]',expand=True)
data.drop(['D1','d2','t'], axis = 1)
print(data.shape)

(14323, 8)

In [ ]:
data[['class','t']]=data['class'].str.split('.',n=1,expand=True)
data.drop(['t'],axis=1)
data.tail()

                                                      D1  ...   TaxId
14318  >d3s2ra_ g.97.1.0 (A:) automated matches {Thal...  ...    3702
14319  >d4c3hd_ g.98.1.1 (D:) RNA polymerase I subuni...  ...    4932
14320  >d3jb9e_ g.99.1.1 (e:) Pre-mRNA splicing facto...  ...  284812
14321  >d5lj3n2 g.100.1.1 (N:6-144) Pre-mRNA splicing...  ...    4932
14322  >d5syba_ g.101.1.1 (A:) Pre-mRNA splicing fact...  ...    9606

[5 rows x 8 columns]

In [ ]:
data=data.drop(['D1','d2','d3','TaxId','t'], axis=1)

In [ ]:
data.shape

(14323, 3)

In [ ]:
data['Descriptor'] = data['d1'].str.cat(data['class'].astype(str), sep="|")

In [ ]:
data.tail()

                                                Sequence  ...  Descriptor
14318  ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...  ...   >d3s2ra|g
14319  sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...  ...   >d4c3hd|g
14320  rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...  ...   >d3jb9e|g
14321  nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...  ...  >d5lj3n2|g
14322  akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...  ...   >d5syba|g

[5 rows x 4 columns]

In [ ]:
data=data[['Descriptor','Sequence']]
data.tail()

       Descriptor                                           Sequence
14318   >d3s2ra|g  ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...
14319   >d4c3hd|g  sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...
14320   >d3jb9e|g  rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...
14321  >d5lj3n2|g  nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...
14322   >d5syba|g  akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences.csv", index=False)

In [ ]:
data.to_csv("/content/sequences.txt", index=False, sep="\n")

In [ ]:
data= data.iloc[:13057,:]
data.tail()

       Descriptor                                           Sequence
13052  >d4ogca3|d  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
13053  >d5axwa3|d  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054  >d4oo8a3|d  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055  >d3jb9a5|d  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
13056   >d5gmkf|d  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d.csv",index=False)

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d.txt", index=False, sep="\n")

In [ ]:
data= pd.read_csv("/content/drive/MyDrive/Project/sequences_d.csv")
data.tail()

       Descriptor                                           Sequence
13052  >d4ogca3|d  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
13053  >d5axwa3|d  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054  >d4oo8a3|d  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055  >d3jb9a5|d  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
13056   >d5gmkf|d  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data["Name Length"]= data["Sequence"].str.len()

In [ ]:
data.tail()

       Descriptor  ... Name Length
13052  >d4ogca3|d  ...         215
13053  >d5axwa3|d  ...         389
13054  >d4oo8a3|d  ...         655
13055  >d3jb9a5|d  ...         651
13056   >d5gmkf|d  ...         115

[5 rows x 3 columns]

In [ ]:
data.describe()

        Name Length
count  13057.000000
mean     184.137015
std      106.112017
min       20.000000
25%      106.000000
50%      153.000000
75%      242.000000
max     1207.000000

In [ ]:
tmp=data['Name Length'].value_counts()

KeyError: ignored

In [ ]:
type(tmp)

pandas.core.series.Series

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13057 entries, 0 to 13056
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Descriptor   13057 non-null  object
 1   Sequence     13057 non-null  object
 2   Name Length  13057 non-null  int64
dtypes: int64(1), object(2)
memory usage: 306.1+ KB

In [ ]:
data.iloc[0,2]

116

In [ ]:
str = data.iloc[13055,1]

In [ ]:
str[0:6]

'lekqln'

In [ ]:
index_to_remove=[]

In [ ]:
for i in range(0,3):
  print(i)

0
1
2

In [ ]:
for i in range(0,13057):
  if(data.iloc[i,2]<242):
    index_to_remove.append(i)

  else:
    seq = data.iloc[i,1]
    data.iloc[i,1]= seq[0:242]

In [ ]:
print(index_to_remove)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 888, 894, 895, 896, 897, 898, 899, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1482, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1656, 1657, 1658, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1741, 1742, 1811, 1812, 1813, 1816, 1823, 1824, 1825, 1827, 1828, 1829, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1849, 1850, 1851, 1852, 1857, 1859, 1861, 1862, 1864, 1866, 1869, 1870, 1871, 1876, 1877, 1880, 1888, 1892, 1893, 1898, 1899, 1900, 1908, 1909, 1910, 1912, 1913, 1914, 1917, 1918, 1920, 1922, 1925, 1926, 1929, 1930, 1931, 1932, 1933, 1934, 1936, 1937, 1938, 1942, 1944, 1945, 1946, 1958, 1961, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1987, 1992, 1994, 1995, 1996, 1997, 1998, 2001, 2002, 2008, 2009, 2010, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2050, 2051, 2053, 2057, 2061, 2063, 2064, 2065, 2066, 2067, 2072, 2073, 2074, 2075, 2076, 2077, 2116, 2117, 2118, 2119, 2121, 2122, 2123, 2124, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2178, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2285, 2286, 2287, 2288, 2289, 2290, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2354, 2355, 2359, 2360, 2361, 2364, 2365, 2366, 2368, 2370, 2371, 2372, 2373, 2374, 2375, 2383, 2384, 2385, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2416, 2417, 2418, 2419, 2420, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2431, 2432, 2433, 2434, 2435, 2437, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2474, 2475, 2476, 2480, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2530, 2532, 2535, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3137, 3139, 3140, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3400, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3477, 3478, 3479, 3480, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3504, 3506, 3507, 3508, 3511, 3512, 3513, 3514, 3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526, 3527, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3561, 3563, 3595, 3597, 3598, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628, 3629, 3630, 3631, 3632, 3633, 3634, 3635, 3636, 3637, 3638, 3639, 3640, 3641, 3642, 3643, 3644, 3645, 3646, 3647, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3667, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3689, 3690, 3691, 3692, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3744, 3745, 3746, 3747, 3748, 3749, 3750, 3751, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3777, 3778, 3781, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3794, 3795, 3796, 3797, 3798, 3799, 3800, 3801, 3802, 3803, 3804, 3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3813, 3814, 3815, 3816, 3817, 3818, 3819, 3820, 3821, 3822, 3823, 3824, 3825, 3826, 3827, 3828, 3829, 3830, 3831, 3832, 3833, 3834, 3835, 3836, 3837, 3838, 3839, 3840, 3841, 3842, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3850, 3851, 3852, 3853, 3854, 3855, 3856, 3857, 3858, 3859, 3860, 3861, 3862, 3863, 3864, 3865, 3866, 3867, 3868, 3869, 3870, 3871, 3872, 3873, 3874, 3875, 3876, 3877, 3878, 3879, 3880, 3881, 3882, 3883, 3884, 3885, 3886, 3887, 3888, 3889, 3890, 3891, 3892, 3893, 3894, 3895, 3896, 3897, 3898, 3899, 3900, 3901, 3902, 3903, 3904, 3905, 3906, 3907, 3908, 3909, 3910, 3911, 3912, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3927, 3928, 3929, 3930, 3931, 3932, 3933, 3934, 3935, 3936, 3937, 3938, 3939, 3940, 3941, 3942, 3943, 3944, 3945, 3946, 3947, 3948, 3949, 3950, 3951, 3952, 3953, 3954, 3955, 3956, 3957, 3958

In [ ]:
data = data.drop(index_to_remove, axis=0)

In [ ]:
data = data.drop(['Name Length'], axis=1)

In [ ]:
data["SeqLength"]= data["Sequence"].str.len()

In [ ]:
data.describe()

       SeqLength
count     3277.0
mean       242.0
std          0.0
min        242.0
25%        242.0
50%        242.0
75%        242.0
max        242.0

In [ ]:
data = data.drop(['SeqLength'], axis=1)

In [ ]:
data.tail()

       Descriptor                                           Sequence
13033  >d2r6ia1|d  mrdllndlseglshpdpilraqiqmqkplpkrfykdvtvadveegg...
13034  >d2pifa1|d  arqsaiaaareargtyrnglvtptagvapgmtqanlialprdwayd...
13053  >d5axwa3|d  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054  >d4oo8a3|d  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055  >d3jb9a5|d  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len242.csv",index=False)

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len242.txt", index=False, sep="\n")

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len242.csv")
df.tail()

      Descriptor                                           Sequence
3272  >d2r6ia1|d  mrdllndlseglshpdpilraqiqmqkplpkrfykdvtvadveegg...
3273  >d2pifa1|d  arqsaiaaareargtyrnglvtptagvapgmtqanlialprdwayd...
3274  >d5axwa3|d  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
3275  >d4oo8a3|d  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
3276  >d3jb9a5|d  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...

In [ ]:
df[['Descriptor','tmp']]=df['Descriptor'].str.split('|',expand=True)
df=df.drop(['tmp'], axis = 1)
df.tail()

     Descriptor                                           Sequence
3272   >d2r6ia1  mrdllndlseglshpdpilraqiqmqkplpkrfykdvtvadveegg...
3273   >d2pifa1  arqsaiaaareargtyrnglvtptagvapgmtqanlialprdwayd...
3274   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
3275   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
3276   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...

In [ ]:
df.to_csv("/content/drive/MyDrive/Project/temp_d.txt", index=False, sep="\n")

#Again creating datsets from txt (new Way)

In [ ]:
header_list = ["D1", "Sequence"]

data=pd.read_csv('/content/drive/MyDrive/Project/astral-scopedom-seqres-gd-sel-gs-bib-40-2.07.fa.txt',sep='$', names=header_list,header=None)
data.head()

,D1,Sequence
0,>d1dlwa_ a.1.1.1 (A:) Protozoan/bacterial hemo...,slfeqlggqaavqavtaqfyaniqadatvatffngidmpnqtnkta...
1,>d2gkma_ a.1.1.1 (A:) Protozoan/bacterial hemo...,gllsrlrkrepisiydkiggheaievvvedffvrvladdqlsaffs...
2,>d1ngka_ a.1.1.1 (A:) Protozoan/bacterial hemo...,ksfydavggaktfdaivsrfyaqvaedevlrrvypeddlagaeerl...
3,>d2bkma_ a.1.1.1 (A:) automated matches {Geoba...,eqwqtlyeaiggeetvaklveafyrrvaahpdlrpifpddltetah...
4,>d4i0va_ a.1.1.1 (A:) automated matches {Synec...,aslyeklggaaavdlavekfygkvladervnrffvntdmakqkqhq...

In [ ]:
data.tail()

,D1,Sequence
14318,>d3s2ra_ g.97.1.0 (A:) automated matches {Thal...,ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...
14319,>d4c3hd_ g.98.1.1 (D:) RNA polymerase I subuni...,sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...
14320,>d3jb9e_ g.99.1.1 (e:) Pre-mRNA splicing facto...,rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...
14321,>d5lj3n2 g.100.1.1 (N:6-144) Pre-mRNA splicing...,nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...
14322,>d5syba_ g.101.1.1 (A:) Pre-mRNA splicing fact...,akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...

In [ ]:
data[['d1','d2']]=data['D1'].str.split(' ', n=1, expand=True) 
data[['class','d3']]=data['d2'].str.split('.', n=1, expand=True)

In [ ]:
data.tail()

,D1,Sequence,d1,d2,class,d3
14318,>d3s2ra_ g.97.1.0 (A:) automated matches {Thal...,ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...,>d3s2ra_,g.97.1.0 (A:) automated matches {Thale cress (...,g,97.1.0 (A:) automated matches {Thale cress (Ar...
14319,>d4c3hd_ g.98.1.1 (D:) RNA polymerase I subuni...,sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...,>d4c3hd_,g.98.1.1 (D:) RNA polymerase I subunit A14 {Ba...,g,98.1.1 (D:) RNA polymerase I subunit A14 {Bake...
14320,>d3jb9e_ g.99.1.1 (e:) Pre-mRNA splicing facto...,rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...,>d3jb9e_,g.99.1.1 (e:) Pre-mRNA splicing factor Cwf14 /...,g,99.1.1 (e:) Pre-mRNA splicing factor Cwf14 / B...
14321,>d5lj3n2 g.100.1.1 (N:6-144) Pre-mRNA splicing...,nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...,>d5lj3n2,g.100.1.1 (N:6-144) Pre-mRNA splicing factor C...,g,100.1.1 (N:6-144) Pre-mRNA splicing factor Cwf...
14322,>d5syba_ g.101.1.1 (A:) Pre-mRNA splicing fact...,akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...,>d5syba_,g.101.1.1 (A:) Pre-mRNA splicing factor Phf5 /...,g,101.1.1 (A:) Pre-mRNA splicing factor Phf5 / R...

In [ ]:
data= data.drop(['D1','d2','d3'], axis = 1)

In [ ]:
 data['Descriptor']= data['d1']

In [ ]:
data=data.drop(['d1'],axis=1)

In [ ]:
data.tail()

                                                Sequence class Descriptor
14318  ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...     g   >d3s2ra_
14319  sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...     g   >d4c3hd_
14320  rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...     g   >d3jb9e_
14321  nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...     g   >d5lj3n2
14322  akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...     g   >d5syba_

In [ ]:
data = data[['Descriptor','Sequence','class']]

In [ ]:
classes = data[['class']]
classes.tail()

      class
14318     g
14319     g
14320     g
14321     g
14322     g

In [ ]:
classes.to_csv("/content/drive/MyDrive/Project/classes.csv",index=False)

In [ ]:
data= data.drop(['class'], axis=1)
data.tail()

      Descriptor                                           Sequence
14318   >d3s2ra_  ginpeirknedkvvdsvvvtelsknitpycrcwrsgtfplcdgscv...
14319   >d4c3hd_  sattlntpvvihatqlpqhvstdevlqflesfidekeniidsttmn...
14320   >d3jb9e_  rlrtsrtkrppdgfdeieptliefqdrmrqientmgkgtktemlap...
14321   >d5lj3n2  nepppniceqclgdeanirmtkipqgseckictlpftlyhfktskr...
14322   >d5syba_  akhhpdlifcrkqagvaigrlcekcdgkcvicdsyvrpstlvricd...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences2_all.csv",index=False)

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences2_all.txt", index=False, sep="\n")

In [ ]:
data= data.iloc[:13057,:]
data.tail()

      Descriptor                                           Sequence
13052   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
13053   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
13056   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences2_d.csv",index=False)
data.to_csv("/content/drive/MyDrive/Project/sequences2_d.txt", index=False, sep="\n")

In [ ]:
classes = classes.iloc[:13057,:]
classes.tail()

      class
13052     d
13053     d
13054     d
13055     d
13056     d

In [ ]:
classes.to_csv("/content/drive/MyDrive/Project/classes_d.csv",index=False)

In [ ]:
data= pd.read_csv("/content/drive/MyDrive/Project/sequences2_d.csv")
data.tail()

      Descriptor                                           Sequence
13052   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
13053   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
13056   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data["Length"]= data["Sequence"].str.len()
data.tail()

      Descriptor                                           Sequence  Length
13052   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...     215
13053   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...     389
13054   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...     655
13055   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...     651
13056   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...     115

In [ ]:
count = data["Length"].value_counts()

In [ ]:
#removing seq length <80 and cutting seq >80
index_to_remove=[]
for i in range(0,13057):
  if(data.iloc[i,2]<80):
    index_to_remove.append(i)

  else:
    seq = data.iloc[i,1]
    data.iloc[i,1]= seq[0:80]

In [ ]:
print(index_to_remove)

[58, 59, 60, 61, 62, 63, 66, 67, 68, 71, 73, 78, 80, 81, 82, 84, 85, 86, 87, 88, 97, 101, 102, 103, 105, 106, 107, 108, 109, 110, 114, 118, 119, 126, 129, 140, 147, 153, 154, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 167, 168, 169, 170, 171, 172, 173, 174, 175, 177, 178, 179, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196, 199, 200, 201, 202, 203, 204, 205, 206, 207, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 242, 243, 246, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 271, 272, 273, 274, 277, 285, 286, 287, 299, 300, 305, 309, 310, 312, 314, 315, 316, 317, 318, 319, 325, 326, 327, 328, 353, 358, 359, 360, 361, 363, 364, 365, 366, 370, 374, 381, 385, 386, 387, 389, 393, 405, 407, 409, 412, 416, 419, 420, 421, 425, 426, 427, 434, 435, 440, 441, 448, 449, 452, 460, 468, 474, 488, 498, 504, 508, 518, 519, 520, 521, 524, 535, 537, 538, 541, 542, 543, 546, 547, 552, 553, 554, 555, 556, 557, 559, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 602, 604, 606, 608, 609, 610, 611, 612, 613, 614, 621, 622, 623, 624, 625, 658, 662, 669, 672, 676, 677, 678, 679, 680, 684, 690, 691, 696, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 715, 718, 719, 721, 723, 724, 725, 731, 732, 733, 734, 735, 736, 739, 741, 743, 746, 747, 748, 751, 755, 757, 759, 761, 762, 763, 765, 766, 775, 776, 779, 804, 824, 918, 919, 925, 974, 977, 978, 979, 980, 982, 983, 984, 987, 989, 991, 992, 1064, 1065, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1086, 1087, 1088, 1089, 1091, 1092, 1095, 1096, 1098, 1099, 1100, 1102, 1103, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1116, 1117, 1124, 1125, 1126, 1129, 1130, 1132, 1133, 1134, 1153, 1154, 1161, 1164, 1165, 1181, 1184, 1188, 1198, 1201, 1203, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1254, 1255, 1258, 1260, 1321, 1322, 1323, 1324, 1325, 1342, 1343, 1346, 1347, 1348, 1349, 1351, 1357, 1358, 1363, 1370, 1372, 1374, 1376, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1398, 1399, 1400, 1402, 1403, 1404, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1415, 1417, 1418, 1419, 1421, 1422, 1423, 1424, 1425, 1428, 1437, 1446, 1451, 1452, 1453, 1455, 1460, 1461, 1462, 1473, 1474, 1477, 1478, 1480, 1482, 1542, 1543, 1691, 1692, 1693, 1811, 1812, 1813, 1823, 1892, 1929, 1934, 1967, 2077, 2118, 2153, 2154, 2155, 2156, 2159, 2160, 2161, 2162, 2166, 2167, 2178, 2186, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2212, 2219, 2227, 2244, 2245, 2247, 2248, 2253, 2255, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2268, 2269, 2276, 2278, 2299, 2303, 2304, 2305, 2309, 2310, 2324, 2325, 2327, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2393, 2401, 2406, 2407, 2409, 2414, 2433, 2442, 2444, 2445, 2451, 2458, 2462, 2490, 2491, 2492, 2493, 2494, 2495, 2512, 2513, 2535, 2600, 2602, 2614, 2966, 3002, 3044, 3048, 3080, 3155, 3166, 3180, 3185, 3204, 3266, 3287, 3447, 3448, 3468, 3617, 3618, 3619, 3620, 3622, 3623, 3624, 3626, 3627, 3628, 3629, 3630, 3631, 3632, 3634, 3636, 3638, 3639, 3640, 3642, 3643, 3644, 3646, 3648, 3649, 3650, 3651, 3652, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3667, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3689, 3690, 3691, 3692, 3693, 3694, 3695, 3696, 3697, 3698, 3704, 3705, 3706, 3707, 3708, 3711, 3712, 3715, 3723, 3724, 3726, 3728, 3729, 3730, 3732, 3741, 3743, 3744, 3745, 3748, 3751, 3753, 3755, 3759, 3760, 3762, 3763, 3764, 3765, 3766, 3767, 3769, 3770, 3773, 3775, 3776, 3777, 3778, 3787, 3788, 3810, 3811, 3842, 3894, 3896, 3897, 3898, 3899, 3903, 3906, 3907, 3908, 3909, 3911, 3912, 3913, 3914, 3918, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3937, 3962, 3963, 3964, 3991, 3992, 3993, 3994, 3997, 3998, 3999, 4003, 4009, 4011, 4012, 4013, 4014, 4017, 4019, 4020, 4021, 4032, 4033, 4041, 4046, 4048, 4049, 4050, 4060, 4074, 4083, 4084, 4085, 4086, 4087, 4089, 4090, 4093, 4094, 4104, 4107, 4108, 4111, 4115, 4117, 4119, 4189, 4201, 4239, 4297, 4360, 4361, 4362, 4363, 4517, 4519, 4520, 4521, 4742, 4743, 4744, 4747, 4748, 4750, 4753, 4754, 4755, 4759, 4764, 4766, 4775, 4780, 4781, 4783, 4784, 4785, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4819, 4876, 4898, 5025, 5032, 5033, 5034, 5036, 5037, 5040, 5047, 5048, 5049, 5056, 5057, 5058, 5059, 5060, 5062, 5063, 5064, 5065, 5084, 5085, 5139, 5140, 5141, 5151, 5177, 5180, 5194, 5195, 5198, 5199, 5292, 5296, 5298, 5300, 5301, 5302, 5303, 5315, 5316, 5317, 5324, 5341, 5343, 5345, 5360, 5361, 5363, 5384, 5385, 5405, 5416, 5420, 5421, 5428, 6017, 6289, 6551, 6915, 6924, 7231, 7232, 7234, 7471, 7475, 7477, 7491, 7504, 7506, 7507, 7508, 7509, 7573, 7606, 7617, 7633, 7646, 7648, 7649, 7651, 7669, 7779, 8457, 9581, 9696, 9697, 9698, 9699, 9701, 9702, 9703, 9704, 9705, 9706, 9707, 9708, 9709, 9710, 9711, 9712, 9713, 9714, 9715, 9716, 9717, 9718, 9719, 9720, 9721, 9722, 9724, 9725, 9726, 9727, 9728, 9805, 9807, 9815, 9817, 9819, 9822, 9823, 9828, 9829, 9831, 9834, 9842, 9855, 9856, 9857, 9859, 9862, 9866, 9867, 9868, 9870, 9871, 9874, 9882, 9885, 9890, 9895, 9896, 9897, 9898, 9899, 9900, 9910, 9938, 9939, 9940, 9943, 9944, 9945, 9974, 9983, 9984, 10001, 10002, 10003, 10077, 10080, 10082, 10171, 10189, 10190, 10191, 10206, 10207, 10208, 10210, 10212, 10218, 10379, 10380, 10381, 10416, 10435, 10450, 10454, 10455, 10456, 10458, 10463, 10465, 10466, 10467, 10469, 10471, 10472, 10474, 10476, 10480, 10481, 10482, 10486, 10487, 10488, 10491, 10503, 10504, 10505, 10508, 10509, 10510, 10511, 10514, 10518, 10519, 10521, 10522, 10535, 10538, 10585, 10588, 10591, 10593, 10596, 10597, 10607, 10614, 10615, 10616, 10619, 10674, 10676, 10678, 10681, 10707, 10710, 10727, 10743, 10749, 10752, 10753, 10755, 10764, 10769, 10778, 10796, 10797, 10805, 10807, 10835, 10837, 10838, 10840, 10841, 10842, 10843, 10855, 10856, 10857, 10858, 10859, 10861, 10862, 10863, 10864, 10865, 10866, 10867, 10868, 10869, 10870, 10872, 10881, 10885, 10886, 10887, 10888, 10890, 10892, 10893, 10894, 10895, 10902, 10916, 10917, 10918, 10919, 10921, 10970, 10974, 10975, 10977, 10978, 10997, 11001, 11002, 11018, 11021, 11030, 11063, 11064, 11065, 11072, 11082, 11083, 11084, 11085, 11088, 11089, 11090, 11094, 11096, 11097, 11100, 11101, 11109, 11121, 11122, 11123, 11126, 11127, 11129, 11138, 11166, 11194, 11195, 11196, 11197, 11207, 11208, 11211, 11213, 11216, 11217, 11282, 11285, 11298, 11465, 11466, 11467, 11468, 11469, 11471, 11815, 11927, 12020, 12023, 12190, 12194, 12527, 12529, 12553, 12554, 12607, 12727, 12755, 12757, 12758, 12759, 12760, 12761, 12781, 12784, 12803, 12804, 12805, 12856, 12869, 12880, 12891, 12896, 12897, 12907, 12908, 12909, 12916, 12922, 12923, 12941, 12953, 12954, 12955, 12957, 12978, 12979, 12980, 12982, 12987, 12988, 12989, 12990, 12997, 13004, 13013, 13015, 13021, 13027, 13043, 13046]

In [ ]:
data = data.drop(index_to_remove, axis=0)
data = data.drop(['Length'],axis=1)
data.tail()

      Descriptor                                           Sequence
13052   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
13053   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
13054   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
13055   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
13056   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11825 entries, 0 to 13056
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Descriptor  11825 non-null  object
 1   Sequence    11825 non-null  object
dtypes: object(2)
memory usage: 277.1+ KB

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len80.csv",index=False)
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len80.txt",index=False, sep="\n")

In [ ]:
classes= pd.read_csv("/content/drive/MyDrive/Project/classes_d.csv")
classes.tail()

      class
13052     d
13053     d
13054     d
13055     d
13056     d

In [ ]:
classes = classes.drop(index_to_remove, axis=0)
classes.tail()

      class
13052     d
13053     d
13054     d
13055     d
13056     d

In [ ]:
classes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11825 entries, 0 to 13056
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   class   11825 non-null  object
dtypes: object(1)
memory usage: 184.8+ KB

In [ ]:
classes.to_csv("/content/drive/MyDrive/Project/classes_len80.csv",index=False)

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len80.csv")

In [ ]:
data.tail()

      Descriptor                                           Sequence
11820   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
11821   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
11822   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
11823   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
11824   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
header_list=['D1']
pssm_list = pd.read_csv('pssm.txt',names=header_list,header=None)

In [ ]:
pssm_list.tail()

                 D1
14226  g2dg5.1.pssm
14227  g2vt1.1.pssm
14228  g3bzy.1.pssm
14229  g3n55.1.pssm
14230      pssm.txt

In [ ]:
pssm_list=pssm_list.iloc[:14185,:]

In [ ]:
pssm_list[['d1','d2']]=pssm_list['D1'].str.split('.', n=1, expand=True) 
pssm_list.tail()

                 D1       d1    d2
14180  d7ahla_.pssm  d7ahla_  pssm
14181  d7mdha2.pssm  d7mdha2  pssm
14182  d7odca1.pssm  d7odca1  pssm
14183  d7odca2.pssm  d7odca2  pssm
14184  d8abpa_.pssm  d8abpa_  pssm

In [ ]:
pssm_list = pssm_list.drop(['D1','d2'], axis=1)

In [ ]:
pssm_list['t']='>'
pssm_list.tail()

            d1  t
14180  d7ahla_  >
14181  d7mdha2  >
14182  d7odca1  >
14183  d7odca2  >
14184  d8abpa_  >

In [ ]:
pssm_list['d1']=pssm_list['t']+pssm_list['d1']

In [ ]:
pssm_list.tail()

             d1  t
14180  >d7ahla_  >
14181  >d7mdha2  >
14182  >d7odca1  >
14183  >d7odca2  >
14184  >d8abpa_  >

In [ ]:
pssm_list = pssm_list.drop(['t'],axis=1)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len80.csv")

In [ ]:
pssm_list.iloc[4,0]

'>d1a04a1'

In [ ]:
#Used to get index of sequences not present in pssm.txt

# index_to_remove=[]
# for i in range(1134,11825):
#   flag=0
#   for j in range(0,14185):
#     if(df.iloc[i,0]==pssm_list.iloc[j,0]):
#       flag=1
#       break
#   if(flag==0):
#     index_to_remove.append(i)

In [ ]:
print(index_to_remove)

[2006, 2173, 2476, 2615, 2745, 2918, 2976, 3222, 3366, 3521, 3536, 3992, 4067, 4351, 4366, 4370, 4373, 4374, 4388, 4403, 5462, 5636, 5637, 5639, 6253, 6268, 7088, 7554, 8598, 9953, 10309, 11056, 11057, 11073, 11074, 11077, 11091, 11092, 11094, 11494, 11784, 11785]

In [ ]:
df1 = pd.DataFrame(index_to_remove,columns =['C1'])
df1.to_csv("/content/drive/MyDrive/Project/index_to_remove_for_pssm.csv",index=False)

In [ ]:
df1= pd.read_csv("/content/drive/MyDrive/Project/index_to_remove_for_pssm.csv")
df1.tail()

       C1
37  11092
38  11094
39  11494
40  11784
41  11785

In [ ]:
df1.shape

(42, 1)

In [ ]:
other_index= [122, 406, 473, 807, 931, 932, 985, 1133]
i1=pd.DataFrame(other_index, columns=['C1'])
i1.tail()

     C1
3   807
4   931
5   932
6   985
7  1133

In [ ]:
i1.shape

(8, 1)

In [ ]:
df1 = pd.concat([i1,df1], axis=0)
print(df1)

       C1
0     122
1     406
2     473
3     807
4     931
5     932
6     985
7    1133
0    2006
1    2173
2    2476
3    2615
4    2745
5    2918
6    2976
7    3222
8    3366
9    3521
10   3536
11   3992
12   4067
13   4351
14   4366
15   4370
16   4373
17   4374
18   4388
19   4403
20   5462
21   5636
22   5637
23   5639
24   6253
25   6268
26   7088
27   7554
28   8598
29   9953
30  10309
31  11056
32  11057
33  11073
34  11074
35  11077
36  11091
37  11092
38  11094
39  11494
40  11784
41  11785

In [ ]:
df1.shape

(50, 1)

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/index_to_remove_for_pssm.csv",index=False)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len80.csv")
classes= pd.read_csv("/content/drive/MyDrive/Project/classes_len80.csv")

In [ ]:
index_to_remove= df1.iloc[:,0].tolist()
print(index_to_remove)

[122, 406, 473, 807, 931, 932, 985, 1133, 2006, 2173, 2476, 2615, 2745, 2918, 2976, 3222, 3366, 3521, 3536, 3992, 4067, 4351, 4366, 4370, 4373, 4374, 4388, 4403, 5462, 5636, 5637, 5639, 6253, 6268, 7088, 7554, 8598, 9953, 10309, 11056, 11057, 11073, 11074, 11077, 11091, 11092, 11094, 11494, 11784, 11785]

In [ ]:
df= df.drop(index_to_remove, axis=0)
classes= classes.drop(index_to_remove, axis=0)

In [ ]:
df.to_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm.csv",index=False)
df.to_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm.txt",index=False, sep="\n")
classes.to_csv("/content/drive/MyDrive/Project/classes_d_len80_forpssm.csv",index=False)

In [ ]:
data= pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm.csv")
data.tail()

      Descriptor                                           Sequence
11770   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
11771   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
11772   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
11773   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
11774   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
sub='x'
data['Index']= data["Sequence"].str.find(sub)
data.tail()

      Descriptor                                           Sequence  Index
11770   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...     -1
11771   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...     -1
11772   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...     -1
11773   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...     -1
11774   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...     -1

In [ ]:
index_to_remove=[]
for i in range(0,11775):
  if(data.iloc[i,-1]!=-1):
    index_to_remove.append(i)

print(index_to_remove)

[608, 892, 1651, 4581, 5633, 7755, 9118, 11025]

In [ ]:
data= data.drop(['Index'], axis=1)

In [ ]:
data.tail()

      Descriptor                                           Sequence
11770   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
11771   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
11772   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
11773   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
11774   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
sub='X'
data['Index']= data["Sequence"].str.find(sub)

for i in range(0,11775):
  if(data.iloc[i,-1]!=-1):
    index_to_remove.append(i)

print(index_to_remove)

[608, 892, 1651, 4581, 5633, 7755, 9118, 11025, 1234, 2340, 2466, 2533, 2823, 2824, 3205, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3614, 3631, 3880, 3932, 3933, 3934, 3935, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4265, 4266, 5462, 5534, 6157, 6172, 6190, 6252, 6254, 6273, 6990, 6991, 6992, 7056, 7058, 7059, 7060, 7061, 7067, 7070, 7071, 7757, 8368, 8369, 9131, 9493, 9494, 9817, 9822, 9824, 9923, 9924, 9925, 10378, 10764, 10765, 10850]

In [ ]:
data = data.drop(index_to_remove,axis=0)

In [ ]:
data=data.drop(['Index'],axis=1)
data.tail()

      Descriptor                                           Sequence
11770   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
11771   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
11772   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
11773   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
11774   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm2.csv",index=False)
data.to_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm2.txt",index=False, sep="\n")

In [ ]:
classes= pd.read_csv("/content/drive/MyDrive/Project/classes_d_len80_forpssm.csv")
classes.tail()

      class
11770     d
11771     d
11772     d
11773     d
11774     d

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/Project/sequences_d_len80_forpssm2.csv") #final sequences
df.tail()

      Descriptor                                           Sequence
11682   >d4ogca3  gsavsrvapdplpgqgsfrrapkcdpefqrfriisivanlrisetk...
11683   >d5axwa3  vennegrrskrgarrlkrrrrhriqrvkkllfdynlltdhselsgi...
11684   >d4oo8a3  aeatrlkrtarrrytrrknrilylqeifsnemakvddsffhrlees...
11685   >d3jb9a5  lekqlnerarkwrasqkskfgvkrkqgyvqtekadlppehlrkimk...
11686   >d5gmkf_  serkainkyyppdynpleaeklsrkmakklktmnkshasirlmtpf...

In [ ]:
classes=classes.drop(index_to_remove,axis=0)
classes.to_csv("/content/drive/MyDrive/Project/classes_d_len80_forpssm2.csv",index=False)

In [ ]:
classes= pd.read_csv("/content/drive/MyDrive/Project/classes_d_len80_forpssm2.csv")  #final classes
classes.tail()

      class
11682     d
11683     d
11684     d
11685     d
11686     d

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/pca_pssm_10.csv')
df1.head()

   protein       pc.1       pc.2  ...       pc.9     pc.10  Unnamed: 11
0  d1dlwa_  -8.133646  17.439004  ... -18.938127  3.695612          NaN
1  d2gkma_ -11.406957   2.648755  ...   2.829889  0.916396          NaN
2  d1ngka_  -7.273047  19.702919  ... -10.068220  1.640007          NaN
3  d2bkma_  -9.158859  17.103605  ...   1.486405 -2.457205          NaN
4  d4i0va_  -3.598942  17.814236  ... -12.588700 -0.212165          NaN

[5 rows x 12 columns]

In [ ]:
df1 =df1.drop(df1.columns[[11]], axis=1)

df1.tail()

       protein       pc.1       pc.2  ...      pc.8      pc.9     pc.10
11682  d4ogca3 -19.198139  -2.158412  ... -4.166423  5.649184 -4.174807
11683  d5axwa3 -18.418969  -4.861045  ... -3.233097  1.631262 -0.902593
11684  d4oo8a3 -23.642802  -6.241342  ...  1.305886  8.635386 -0.366495
11685  d3jb9a5 -23.149615 -10.357959  ...  1.765048 -3.970953  2.994734
11686  d5gmkf_ -27.678115  -5.570067  ... -7.336879 -0.201441  5.076239

[5 rows x 11 columns]

In [ ]:
df1=df1.drop(df1.columns[[0]],axis=1)

In [ ]:
df1 = pd.concat([df1,classes], axis=1)
df1.tail()

            pc.1       pc.2      pc.3  ...      pc.9     pc.10  class
11682 -19.198139  -2.158412 -0.642224  ...  5.649184 -4.174807      d
11683 -18.418969  -4.861045 -3.597764  ...  1.631262 -0.902593      d
11684 -23.642802  -6.241342  1.177693  ...  8.635386 -0.366495      d
11685 -23.149615 -10.357959 -6.573455  ... -3.970953  2.994734      d
11686 -27.678115  -5.570067 -1.728095  ... -0.201441  5.076239      d

[5 rows x 11 columns]

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/output_pca_pssm_10.csv",index=False)

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/pca_pssm_3.csv')
df1 =df1.drop(df1.columns[[4]], axis=1)
df1=df1.drop(df1.columns[[0]],axis=1)
df1 = pd.concat([df1,classes], axis=1)
df1.tail()
df1.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/output_pca_pssm_3.csv",index=False)