In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/output_CTDT.csv')
data[['d1','class']]=data.iloc[:,0].str.split('|', n=1, expand=True)
data = data.drop(data.columns[[0]],axis = 1)
data=data.drop(['d1'], axis=1)
data.tail()
data = data.iloc[:13057,:]
data.tail()
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/CTDT_d.csv", index=False)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/output_AAC.csv')
data[['d1','class']]=data.iloc[:,0].str.split('|', n=1, expand=True)
data = data.drop(data.columns[[0]],axis = 1)
data=data.drop(['d1'], axis=1)
data.tail()
data = data.iloc[:13057,:]
data.tail()
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/AAC_d.csv", index=False)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/output_CTriad.csv')
data[['d1','class']]=data.iloc[:,0].str.split('|', n=1, expand=True)
data = data.drop(data.columns[[0]],axis = 1)
data=data.drop(['d1'], axis=1)
data.tail()
data = data.iloc[:13057,:]
data.tail()
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/CTriad_d.csv", index=False)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/output_GAAC.csv')
data[['d1','class']]=data.iloc[:,0].str.split('|', n=1, expand=True)
data = data.drop(data.columns[[0]],axis = 1)
data=data.drop(['d1'], axis=1)
data.tail()
data = data.iloc[:13057,:]
data.tail()
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/GAAC_d.csv", index=False)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/output_CTDC.csv')
data[['d1','class']]=data.iloc[:,0].str.split('|', n=1, expand=True)
data = data.drop(data.columns[[0]],axis = 1)
data=data.drop(['d1'], axis=1)
data.tail()
data = data.iloc[:13057,:]
data.tail()
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/CTDC_d.csv", index=False)

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/AAC_d.csv')
df1=df1.drop(['class'],axis=1)

df2 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/GAAC_d.csv')
df2=df2.drop(['class'],axis=1)

df3 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/CTDC_d.csv')
df3=df3.drop(['class'],axis=1)

df4 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/CTDT_d.csv')
df4=df4.drop(['class'],axis=1)

df5 = pd.read_csv('/content/drive/MyDrive/Project/output_csv_iFeature/CTriad_d.csv')

data = pd.concat([df1, df2, df3, df4, df5], axis=1)
data.tail()

              A         C         D  ...  g7.g7.g6  g7.g7.g7  class
13052  0.111628  0.009302  0.097674  ...       0.0       0.0      d
13053  0.046272  0.002571  0.051414  ...       0.0       0.0      d
13054  0.056489  0.000000  0.080916  ...       0.0       0.0      d
13055  0.053763  0.007680  0.056836  ...       0.0       0.0      d
13056  0.052174  0.034783  0.034783  ...       0.0       0.0      d

[5 rows x 447 columns]

In [ ]:
data.to_csv("/content/drive/MyDrive/Project/output_csv_iFeature/Combined_d.csv", index=False)

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Project/Features_PSSM/output_AAC_PSSM.csv')
df.head()

       V1      V2      V3      V4  ...     V19     V20       d1  class
0 -0.9358 -1.1131 -1.3547 -1.3731  ... -1.5291 -1.2630  d12asa_      d
1 -0.3848 -0.8455 -1.0393 -1.3680  ... -1.1629 -0.9747  d16vpa_      d
2 -0.6795 -0.4744 -0.7821 -1.2179  ... -1.1026 -0.8205  d1914a1      d
3 -0.4330 -0.4330 -0.8557 -1.2887  ... -1.3814 -0.7216  d1914a2      d
4 -1.3881 -1.6269 -2.5821 -3.0299  ... -3.3881 -2.0896  d1a04a1      a

[5 rows x 22 columns]

In [ ]:
df.tail()

           V1      V2      V3      V4  ...     V19     V20       d1  class
14225 -0.5810 -1.2381 -0.9238 -0.8952  ... -1.6095 -0.6476  g2a73.1      b
14226 -0.9428 -2.4410 -2.0996 -2.5793  ... -2.6734 -2.1679  g2dg5.1      d
14227 -0.5243 -1.6214 -2.2621 -2.2816  ... -1.9612 -0.8155  g2vt1.1      d
14228 -0.6238 -1.6535 -2.0495 -2.0990  ... -1.8218 -0.8713  g3bzy.1      d
14229 -0.6218 -1.4538 -0.7059 -1.1261  ... -1.3613 -0.4874  g3n55.1      b

[5 rows x 22 columns]

In [ ]:
classes = df[['class']]
classes.head()

  class
0     d
1     d
2     d
3     d
4     a

In [ ]:
classes.to_csv("/content/drive/MyDrive/Project/Features_PSSM/classes.csv",index=False)

#Data related to PSSM features

GREY PSSM

In [ ]:
labels=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/classes.csv")
labels.tail()

      class
14225     b
14226     d
14227     d
14228     d
14229     b

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/grey_pssm_feature.csv")
df.tail()

       Unnamed: 0      V1      V2      V3  ...     V97     V98     V99    V100
14225       14226  0.0381  0.0190  0.0286  ...  0.0000 -0.1158  0.0005 -0.0330
14226       14227  0.1052  0.0258  0.0480  ... -0.0079 -0.0681  0.0000 -0.0160
14227       14228  0.0680  0.0485  0.0485  ... -0.0058 -0.0998  0.0001 -0.0327
14228       14229  0.0792  0.0198  0.0396  ... -0.0074 -0.0528  0.0001 -0.0172
14229       14230  0.0420  0.0084  0.0588  ... -0.0048 -0.0964 -0.0001 -0.0405

[5 rows x 101 columns]

In [ ]:
df=df.drop(df.columns[0], axis=1)
df.head()

       V1      V2      V3      V4  ...     V97     V98     V99    V100
0  0.0887  0.0581  0.0092  0.0734  ... -0.0039 -0.0790  0.0000 -0.0254
1  0.1124  0.1011  0.0281  0.0590  ... -0.0104 -0.0430  0.0000 -0.0145
2  0.0641  0.0769  0.0256  0.0769  ... -0.0127 -0.1325  0.0004 -0.0397
3  0.0412  0.0825  0.0412  0.0309  ... -0.0049 -0.0571 -0.0001 -0.0227
4  0.0597  0.1045  0.0299  0.0448  ...  0.0000 -0.1198  0.0020 -0.0170

[5 rows x 100 columns]

In [ ]:
df1= pd.concat([df,labels], axis=1)

       V1      V2      V3      V4  ...     V97     V98     V99    V100
0  0.0887  0.0581  0.0092  0.0734  ... -0.0039 -0.0790  0.0000 -0.0254
1  0.1124  0.1011  0.0281  0.0590  ... -0.0104 -0.0430  0.0000 -0.0145
2  0.0641  0.0769  0.0256  0.0769  ... -0.0127 -0.1325  0.0004 -0.0397
3  0.0412  0.0825  0.0412  0.0309  ... -0.0049 -0.0571 -0.0001 -0.0227
4  0.0597  0.1045  0.0299  0.0448  ...  0.0000 -0.1198  0.0020 -0.0170

[5 rows x 100 columns]

In [ ]:
df1.tail()

           V1      V2      V3      V4  ...     V98     V99    V100  class
14225  0.0381  0.0190  0.0286  0.0857  ... -0.1158  0.0005 -0.0330      b
14226  0.1052  0.0258  0.0480  0.0701  ... -0.0681  0.0000 -0.0160      d
14227  0.0680  0.0485  0.0485  0.0388  ... -0.0998  0.0001 -0.0327      d
14228  0.0792  0.0198  0.0396  0.0693  ... -0.0528  0.0001 -0.0172      d
14229  0.0420  0.0084  0.0588  0.0756  ... -0.0964 -0.0001 -0.0405      b

[5 rows x 101 columns]

In [ ]:
df1 = df1[df1['class'] != 'x']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB

In [ ]:
df1

            V1       V2       V3       V4  ...    V398  V399    V400  class
0      13.0000   9.1111   8.1667   8.2222  ...  0.0000   0.0  0.0000      d
1      21.3333   8.0000   5.3333   5.3333  ...  0.9333   2.8  7.4667      d
2       2.4706   1.1176   1.2353   1.0000  ...  0.0000   0.0  0.0000      d
3       2.4167   0.7500   0.9167   0.7500  ...  0.0000   0.0  0.0000      d
4       2.8947   0.6842   0.5789   0.5263  ...  0.0000   0.0  0.0000      a
...        ...      ...      ...      ...  ...     ...   ...     ...    ...
14225   2.2857   0.8571   0.5714   0.5714  ...  0.0000   0.0  0.0000      b
14226  38.2727  20.8636  20.5000  19.0455  ...  0.0000   0.0  0.0000      d
14227   4.5000   2.0000   2.1111   1.9444  ...  0.0000   0.0  0.0000      d
14228   5.0000   1.7895   1.7368   1.6316  ...  0.0000   0.0  0.0000      d
14229   2.8571   1.2857   1.3571   1.2857  ...  0.0000   0.0  0.0000      b

[13035 rows x 401 columns]

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/Features_PSSM/GREY_PSSM.csv", index=False)

PSSM400

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/pssm400.csv")
df.tail()

       Unnamed: 0       V1       V2       V3  ...  V397  V398  V399  V400
14225       14226   2.2857   0.8571   0.5714  ...   0.0   0.0   0.0   0.0
14226       14227  38.2727  20.8636  20.5000  ...   0.0   0.0   0.0   0.0
14227       14228   4.5000   2.0000   2.1111  ...   0.0   0.0   0.0   0.0
14228       14229   5.0000   1.7895   1.7368  ...   0.0   0.0   0.0   0.0
14229       14230   2.8571   1.2857   1.3571  ...   0.0   0.0   0.0   0.0

[5 rows x 401 columns]

In [ ]:
df=df.drop(df.columns[0], axis=1)
df.head()

        V1      V2      V3      V4  ...    V397    V398  V399    V400
0  13.0000  9.1111  8.1667  8.2222  ...  0.0000  0.0000   0.0  0.0000
1  21.3333  8.0000  5.3333  5.3333  ...  3.7333  0.9333   2.8  7.4667
2   2.4706  1.1176  1.2353  1.0000  ...  0.0000  0.0000   0.0  0.0000
3   2.4167  0.7500  0.9167  0.7500  ...  0.0000  0.0000   0.0  0.0000
4   2.8947  0.6842  0.5789  0.5263  ...  0.0000  0.0000   0.0  0.0000

[5 rows x 400 columns]

In [ ]:
df1= pd.concat([df,labels], axis=1)
df1.tail()

            V1       V2       V3       V4  ...  V398  V399  V400  class
14225   2.2857   0.8571   0.5714   0.5714  ...   0.0   0.0   0.0      b
14226  38.2727  20.8636  20.5000  19.0455  ...   0.0   0.0   0.0      d
14227   4.5000   2.0000   2.1111   1.9444  ...   0.0   0.0   0.0      d
14228   5.0000   1.7895   1.7368   1.6316  ...   0.0   0.0   0.0      d
14229   2.8571   1.2857   1.3571   1.2857  ...   0.0   0.0   0.0      b

[5 rows x 401 columns]

In [ ]:
df1 = df1[df1['class'] != 'x']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/Features_PSSM/PSSM400.csv", index=False)

AB_pssm

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/AB_pssm.csv")
df.tail()

       Unnamed: 0      V1      V2      V3  ...    V397    V398    V399    V400
14225       14226 -0.2000 -2.2000 -0.8000  ... -0.3000 -2.5000 -1.4000 -0.4000
14226       14227  0.5926 -2.1481 -2.5185  ... -1.8966 -3.0345 -2.3793 -2.1379
14227       14228 -0.2000 -0.6000 -2.4000  ... -3.2500 -2.3750 -0.5000 -0.2500
14228       14229 -0.4000  0.4000 -0.8000  ... -2.6667 -1.5000 -0.3333 -1.1667
14229       14230  0.0000 -1.8000 -1.4000  ...  0.2083 -2.8750 -1.5417 -0.6250

[5 rows x 401 columns]

In [ ]:
df=df.drop(df.columns[0], axis=1)
df.head()

       V1      V2      V3      V4  ...    V397    V398    V399    V400
0 -0.9375 -0.8750 -1.6250 -1.9375  ... -0.8696 -2.4783 -1.8696 -0.6087
1 -0.2353 -1.2353 -1.2353 -1.6471  ... -0.6667 -2.7879 -1.6667 -1.2424
2 -1.3333 -1.0000  0.3333 -1.0000  ... -0.7143 -2.4762 -1.1905 -0.6667
3 -1.0000 -1.7500 -2.7500 -3.5000  ... -0.5238 -2.2381 -1.0000 -1.0476
4 -1.6667  0.0000 -1.0000  3.6667  ... -1.9000 -2.9000 -1.5000 -0.4000

[5 rows x 400 columns]

In [ ]:
df1= pd.concat([df,labels], axis=1)
df1.tail()

           V1      V2      V3      V4  ...    V398    V399    V400  class
14225 -0.2000 -2.2000 -0.8000 -0.2000  ... -2.5000 -1.4000 -0.4000      b
14226  0.5926 -2.1481 -2.5185 -3.1111  ... -3.0345 -2.3793 -2.1379      d
14227 -0.2000 -0.6000 -2.4000 -2.8000  ... -2.3750 -0.5000 -0.2500      d
14228 -0.4000  0.4000 -0.8000 -3.0000  ... -1.5000 -0.3333 -1.1667      d
14229  0.0000 -1.8000 -1.4000 -2.0000  ... -2.8750 -1.5417 -0.6250      b

[5 rows x 401 columns]

In [ ]:
df1 = df1[df1['class'] != 'x']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/Features_PSSM/AB_PSSM.csv", index=False)

Discrete_cosine

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/Discrete_cosine.csv")
df.tail()

       Unnamed: 0      V1      V2      V3  ...    V397    V398    V399    V400
14225       14226  5.5130  1.7498  0.1940  ...  0.8975  0.6068 -0.5769  0.5609
14226       14227  6.1767  1.9361 -0.2618  ... -1.4842  0.1105 -0.5661  1.2490
14227       14228  4.6730 -1.2496 -1.6601  ...  0.1116  1.3569 -1.1917  0.3662
14228       14229  6.6466  1.7234  0.5494  ... -0.6276  0.7958 -0.6276  0.7273
14229       14230  3.8496  1.0539  0.1744  ...  0.4705  1.0053 -0.3285  0.0916

[5 rows x 401 columns]

In [ ]:
df=df.drop(df.columns[0], axis=1)
df.head()

       V1      V2      V3      V4  ...    V397    V398    V399    V400
0  6.7781  0.5356  1.0983  0.9109  ...  0.9236 -0.5860 -0.2717  0.5368
1  7.6633  1.0314  0.6250  0.7211  ...  0.9977 -0.1461 -0.3024  0.5874
2  5.5164 -2.3461 -0.2169  0.1088  ...  0.7829 -0.6804 -0.4631  0.4544
3  6.8421 -0.9894 -1.0977  0.4362  ... -0.4276  0.8477  0.1397  0.3491
4  3.8752  1.9692 -0.4877 -1.4799  ... -2.3688 -0.8678 -0.1830 -0.6329

[5 rows x 400 columns]

In [ ]:
df1= pd.concat([df,labels], axis=1)
df1.tail()

           V1      V2      V3      V4  ...    V398    V399    V400  class
14225  5.5130  1.7498  0.1940 -0.6628  ...  0.6068 -0.5769  0.5609      b
14226  6.1767  1.9361 -0.2618 -0.3771  ...  0.1105 -0.5661  1.2490      d
14227  4.6730 -1.2496 -1.6601  0.4356  ...  1.3569 -1.1917  0.3662      d
14228  6.6466  1.7234  0.5494 -0.3411  ...  0.7958 -0.6276  0.7273      d
14229  3.8496  1.0539  0.1744 -0.1114  ...  1.0053 -0.3285  0.0916      b

[5 rows x 401 columns]

In [ ]:
df1 = df1[df1['class'] != 'x']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/Features_PSSM/DISCRETE_COSINE_PSSM.csv", index=False)

rpssm

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/rpssm.csv")
df.tail()

       Unnamed: 0      V1       V2       V3  ...     V107    V108     V109     V110
14225       14226  2.3558   3.6261   4.8492  ...   2.9498  3.4146   5.4498   4.9047
14226       14227  9.5781  10.7019  11.3658  ...  10.4502  5.2802  15.8761  14.8015
14227       14228  6.4096   8.3931   9.6166  ...   7.6456  4.1964   7.5608  11.1109
14228       14229  6.2961   7.5082   8.5778  ...   6.9789  4.2545   7.5389  10.8825
14229       14230  3.5753   3.5210   4.3666  ...   2.4194  2.9341   6.5654   6.0306

[5 rows x 111 columns]

In [ ]:
df=df.drop(df.columns[0], axis=1)
df.head()

       V1       V2       V3      V4  ...     V107    V108     V109    V110
0  5.0053   6.1153   6.3599  4.2916  ...   5.2186  4.5182   7.5705  6.3509
1  3.8341   4.4322   4.2507  3.7300  ...   3.2138  3.3810   4.6420  6.0746
2  4.1623   4.7592   5.5265  3.4740  ...   5.4427  6.4707   1.8253  2.0999
3  2.8229   3.1888   2.9809  3.4097  ...   4.6449  2.9616   4.3529  5.6420
4  5.6423  11.5362  11.8506  8.2534  ...  12.6331  6.0392  11.1063  6.6220

[5 rows x 110 columns]

In [ ]:
df1= pd.concat([df,labels], axis=1)
df1.tail()

           V1       V2       V3      V4  ...    V108     V109     V110  class
14225  2.3558   3.6261   4.8492  2.8958  ...  3.4146   5.4498   4.9047      b
14226  9.5781  10.7019  11.3658  8.7541  ...  5.2802  15.8761  14.8015      d
14227  6.4096   8.3931   9.6166  5.3976  ...  4.1964   7.5608  11.1109      d
14228  6.2961   7.5082   8.5778  5.2894  ...  4.2545   7.5389  10.8825      d
14229  3.5753   3.5210   4.3666  3.4426  ...  2.9341   6.5654   6.0306      b

[5 rows x 111 columns]

In [ ]:
df1 = df1[df1['class'] != 'x']
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 111 entries, V1 to class
dtypes: float64(110), object(1)
memory usage: 11.1+ MB

In [ ]:
df1.to_csv("/content/drive/MyDrive/Project/Features_PSSM/RPSSM_PSSM.csv", index=False)

/content

In [ ]:
!pwd

/content

In [ ]:
%cd /content/drive/MyDrive/Project/Features_PSSM

/content/drive/MyDrive/Project/Features_PSSM

In [ ]:
!pwd

/content/drive/MyDrive/Project/Features_PSSM

In [ ]:
df=pd.read_csv("aadp_pssm.csv")
df.head()

   Unnamed: 0      V1      V2      V3  ...    V417     V418    V419    V420
0           1 -0.9358 -1.1131 -1.3547  ...  1.0890   3.7883  2.1135  1.3037
1           2 -0.3848 -0.8455 -1.0393  ...  0.4225   2.2394  1.2000  0.6789
2           3 -0.6795 -0.4744 -0.7821  ...  0.1429   2.0260  0.7922  0.5195
3           4 -0.4330 -0.4330 -0.8557  ...  0.3542   2.0729  1.4375  0.7604
4           5 -1.3881 -1.6269 -2.5821  ...  3.5909  11.1061  7.9091  1.8182

[5 rows x 421 columns]

In [ ]:
labels=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/classes.csv")
labels.tail()

      class
14225     b
14226     d
14227     d
14228     d
14229     b

In [ ]:
def create_csv(filename, output_file):
  print(filename)
  print()
  df=pd.read_csv(filename)
  df.tail()
  df=df.drop(df.columns[0], axis=1)
  df1= pd.concat([df,labels], axis=1)
  df1 = df1[df1['class'] != 'x']
  df1.info()
  df1.to_csv(output_file, index=False)

In [ ]:
!pwd

/content/drive/MyDrive/Project/Features_PSSM

In [ ]:
filenames= ['aadp_pssm.csv', 'dpc_pssm.csv', 'dfmca_pssm.csv', 'lpc_pssm.csv', 'mbmgac_pssm.csv']
output_files= ['AADP_PSSM.csv', 'DPC_PSSM.csv', 'DFMCA_PSSM.csv', 'LPC_PSSM.csv', 'MBMGAC_PSSM.csv']

In [ ]:
length = len(filenames)
print(length)

5

In [ ]:
for i in range(length):
  create_csv(filenames[i],output_files[i])

aadp_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 421 entries, V1 to class
dtypes: float64(420), object(1)
memory usage: 42.0+ MB
dpc_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB
dfmca_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 211 entries, V1 to class
dtypes: float64(210), object(1)
memory usage: 21.1+ MB
lpc_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 281 entries, V1 to class
dtypes: float64(260), int64(20), object(1)
memory usage: 28.0+ MB
mbmgac_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 561 entries, V1 to class
dtypes: float64(560), object(1)
memory usage: 55.9+ MB

In [ ]:
filenames= ['soma_pssm.csv', 'single_average_pssm.csv', 'svd_pssm.csv']
output_files= ['SOMA_PSSM.csv', 'SINGLE_AVERAGE_PSSM.csv', 'SVD_PSSM.csv']

In [ ]:
length = len(filenames)
print(length)

3

In [ ]:
for i in range(length):
  create_csv(filenames[i],output_files[i])

soma_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 161 entries, V1 to class
dtypes: float64(160), object(1)
memory usage: 16.1+ MB
single_average_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, V1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB
svd_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      13035 non-null  float64
 1   V2      13035 non-null  float64
 2   V3      13035 non-null  float64
 3   V4      13035 non-null  float64
 4   V5      13035 non-null  float64
 5   V6      13035 non-null  float64
 6   V7      13035 non-null  float64
 7   V8      13035 non-null  float64
 8   V9      13035 non-null  float64
 9   V10     13035 non-null  float64
 10  V11     13035 non-null  float64
 11  V12     13035 non-null  float64
 12  V13     13035 non-null  float64
 13  V14     13035 non-null  float64
 14  V15     13035 non-null  float64
 15  V16     13035 non-null  float64
 16  V17     13035 non-null  float64
 17  V18     13035 non-null  float64
 18  V19     13035 non-null  float64
 19  V20     13035 non-null  float64
 20  class   13035 non-null  object
dtypes: float64(20), object(1)
memory usage: 2.2+ MB

#For some more pssm features extracted by sir

In [ ]:
df1=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/AB_pssm2.csv")
df1.head()

   Unnamed: 0 pssm_short_names  ...    V399    V400
0           1     d12asa_.pssm  ... -1.8696 -0.6087
1           2     d16vpa_.pssm  ... -1.6667 -1.2424
2           3     d1914a1.pssm  ... -1.1905 -0.6667
3           4     d1914a2.pssm  ... -1.0000 -1.0476
4           5     d1a04a1.pssm  ... -1.5000 -0.4000

[5 rows x 404 columns]

In [ ]:
df2=pd.read_csv("/content/drive/MyDrive/Project/PSSM Features/scsh2.csv", header=None)
df2.head()

            0    1    2    3    4    5    ...  395  396  397  398  399  400
0  d12asa_.pssm    1    1    1    1    1  ...    0    0    1    1    0    0
1  d16vpa_.pssm    1    0    1    1    1  ...    1    1    0    1    0    1
2  d1914a1.pssm    1    0    1    1    0  ...    1    1    0    0    0    0
3  d1914a2.pssm    0    0    0    1    0  ...    0    1    1    0    0    0
4  d1a04a1.pssm    1    0    0    0    0  ...    0    0    0    0    0    0

[5 rows x 401 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14230 entries, 0 to 14229
Columns: 401 entries, 0 to 400
dtypes: int64(400), object(1)
memory usage: 43.5+ MB

In [ ]:
labels=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/classes.csv")
labels.tail()

      class
14225     b
14226     d
14227     d
14228     d
14229     b

In [ ]:
filenames=['AATP_TPCC.csv', 'k_seperated_bigrame.csv', 'CS_PSe_PSSM.csv', 'dwt_PSSM.csv', 'EDP_MEDP.csv',  'FPSSM.csv', 'PSSMBLOCK.csv', 'scsh2.csv', 'trigrame_pssm.csv']
!pwd

/content

In [ ]:
%cd /content/drive/MyDrive/Project/PSSM Features

/content/drive/.shortcut-targets-by-id/1h10rNk1ZqAojpl6hDsas-ooVdWgH6mg6/PSSM Features

In [ ]:
output_files= ['/content/drive/MyDrive/Project/Features_PSSM/AATP_TPCC.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/K_SEPERATED_BIGRAME.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/CS_PSE_PSSM.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/DWT_PSSM.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/EDP_MEDP.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/FPSSM.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/PSSMBLOCK.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/SCSH2.csv',
               '/content/drive/MyDrive/Project/Features_PSSM/TRIGRAME_PSSM.csv'
               ]

In [ ]:
size=len(filenames)
print(size)

9

In [ ]:
df1.head()

   Unnamed: 0 pssm_short_names  ...    V399    V400
0           1     d12asa_.pssm  ... -1.8696 -0.6087
1           2     d16vpa_.pssm  ... -1.6667 -1.2424
2           3     d1914a1.pssm  ... -1.1905 -0.6667
3           4     d1914a2.pssm  ... -1.0000 -1.0476
4           5     d1a04a1.pssm  ... -1.5000 -0.4000

[5 rows x 404 columns]

In [ ]:
for i in range(size):
  df2=pd.read_csv(filenames[i],header=None)
  res= df1.iloc[:,1].equals(df2.iloc[:,0])
  print(res)

True
True
True
True
True
True
True
True
False

In [ ]:
df2=pd.read_csv(filenames[8],header=None)
df2.tail()

               0        1        2     ...    7998     7999     8000
14225  g2a73.1.pssm   5.4510   3.9721  ...  1.4318   2.9342   7.0830
14226  g2dg5.1.pssm  33.7641  18.1280  ...  7.5101  11.4797  13.9507
14227  g2vt1.1.pssm   5.7891   4.6027  ...  1.0158   3.0971   5.9094
14228  g3bzy.1.pssm   4.5286   3.8920  ...  1.0351   2.1900   5.4174
14229  g3n55.1.pssm   5.5252   3.4844  ...  2.6415   4.9481   9.0159

[5 rows x 8001 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14230 entries, 0 to 14229
Columns: 8001 entries, 0 to 8000
dtypes: float64(8000), object(1)
memory usage: 868.6+ MB

In [ ]:
df1.iloc[:,1].equals(df2.iloc[:,0])

False

In [ ]:
def create_csv2(filename, output_file):
  print(filename)
  print()
  df=pd.read_csv(filename,header=None)
  df.tail()
  df=df.drop(df.columns[0], axis=1)
  df1= pd.concat([df,labels], axis=1)
  df1 = df1[df1['class'] != 'x']
  df1.info()
  df1.to_csv(output_file, index=False)

In [ ]:
for i in range(size):
  create_csv2(filenames[i],output_files[i])

AATP_TPCC.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 421 entries, 1 to class
dtypes: float64(420), object(1)
memory usage: 42.0+ MB
k_seperated_bigrame.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, 1 to class
dtypes: float64(400), object(1)
memory usage: 40.0+ MB
CS_PSe_PSSM.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 701 entries, 1 to class
dtypes: float64(700), object(1)
memory usage: 69.8+ MB
dwt_PSSM.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Data columns (total 81 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       13035 non-null  float64
 1   2       13035 non-null  float64
 2   3       13035 non-null  float64
 3   4       13035 non-null  float64
 4   5       13035 non-null  float64
 5   6       13035 non-null  float64
 6   7       13035 non-null  float64
 7   8       13035 non-null  float64
 8   9       13035 non-null  float64
 9   10      13035 non-null  float64
 10  11      13035 non-null  float64
 11  12      13035 non-null  float64
 12  13      13035 non-null  float64
 13  14      13035 non-null  float64
 14  15      13035 non-null  float64
 15  16      13035 non-null  float64
 16  17      13035 non-null  float64
 17  18      13035 non-null  float64
 18  19      13035 non-null  float64
 19  20      13035 non-null  float64
 20  21      13035 non-null  float64
 21  22      13035 non-null  float64
 22  23      13035 non-null  float64
 23  24      13035 non-null  float64
 24  25      13035 non-null  float64
 25  26      13035 non-null  float64
 26  27      13035 non-null  float64
 27  28      13035 non-null  float64
 28  29      13035 non-null  float64
 29  30      13035 non-null  float64
 30  31      13035 non-null  float64
 31  32      13035 non-null  float64
 32  33      13035 non-null  float64
 33  34      13035 non-null  float64
 34  35      13035 non-null  float64
 35  36      13035 non-null  float64
 36  37      13035 non-null  float64
 37  38      13035 non-null  float64
 38  39      13035 non-null  float64
 39  40      13035 non-null  float64
 40  41      13035 non-null  float64
 41  42      13035 non-null  float64
 42  43      13035 non-null  float64
 43  44      13035 non-null  float64
 44  45      13035 non-null  float64
 45  46      13035 non-null  float64
 46  47      13035 non-null  float64
 47  48      13035 non-null  float64
 48  49      13035 non-null  float64
 49  50      13035 non-null  float64
 50  51      13035 non-null  float64
 51  52      13035 non-null  float64
 52  53      13035 non-null  float64
 53  54      13035 non-null  float64
 54  55      13035 non-null  float64
 55  56      13035 non-null  float64
 56  57      13035 non-null  float64
 57  58      13035 non-null  float64
 58  59      13035 non-null  float64
 59  60      13035 non-null  float64
 60  61      13035 non-null  float64
 61  62      13035 non-null  float64
 62  63      13035 non-null  float64
 63  64      13035 non-null  float64
 64  65      13035 non-null  float64
 65  66      13035 non-null  float64
 66  67      13035 non-null  float64
 67  68      13035 non-null  float64
 68  69      13035 non-null  float64
 69  70      13035 non-null  float64
 70  71      13035 non-null  float64
 71  72      13035 non-null  float64
 72  73      13035 non-null  float64
 73  74      13035 non-null  float64
 74  75      13035 non-null  float64
 75  76      13035 non-null  float64
 76  77      13035 non-null  float64
 77  78      13035 non-null  float64
 78  79      13035 non-null  float64
 79  80      13035 non-null  float64
 80  class   13035 non-null  object
dtypes: float64(80), object(1)
memory usage: 8.2+ MB
EDP_MEDP.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 421 entries, 1 to class
dtypes: float64(420), object(1)
memory usage: 42.0+ MB
FPSSM.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 421 entries, 1 to class
dtypes: int64(420), object(1)
memory usage: 42.0+ MB
PSSMBLOCK.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 301 entries, 1 to class
dtypes: float64(300), object(1)
memory usage: 30.0+ MB
scsh2.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 401 entries, 1 to class
dtypes: int64(400), object(1)
memory usage: 40.0+ MB
trigrame_pssm.csv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13035 entries, 0 to 14229
Columns: 8001 entries, 1 to class
dtypes: float64(8000), object(1)
memory usage: 795.8+ MB

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Project/PSSM Features/trigrame_pssm.csv', header=None)
df1.tail()

               0        1        2     ...    7998     7999     8000
14225  g2a73.1.pssm   5.4510   3.9721  ...  1.4318   2.9342   7.0830
14226  g2dg5.1.pssm  33.7641  18.1280  ...  7.5101  11.4797  13.9507
14227  g2vt1.1.pssm   5.7891   4.6027  ...  1.0158   3.0971   5.9094
14228  g3bzy.1.pssm   4.5286   3.8920  ...  1.0351   2.1900   5.4174
14229  g3n55.1.pssm   5.5252   3.4844  ...  2.6415   4.9481   9.0159

[5 rows x 8001 columns]

In [ ]:
df2=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/AB_pssm2.csv")
df2.head()

   Unnamed: 0 pssm_short_names  ...    V399    V400
0           1     d12asa_.pssm  ... -1.8696 -0.6087
1           2     d16vpa_.pssm  ... -1.6667 -1.2424
2           3     d1914a1.pssm  ... -1.1905 -0.6667
3           4     d1914a2.pssm  ... -1.0000 -1.0476
4           5     d1a04a1.pssm  ... -1.5000 -0.4000

[5 rows x 404 columns]

In [ ]:
df=df1[[0]]
df.head()

              0
0  d12asa_.pssm
1  d16vpa_.pssm
2  d1914a1.pssm
3  d1914a2.pssm
4  d1a04a1.pssm

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14230 entries, 0 to 14229
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       14229 non-null  object
dtypes: object(1)
memory usage: 111.3+ KB

In [ ]:
df2.iloc[:,1]

0        d12asa_.pssm
1        d16vpa_.pssm
2        d1914a1.pssm
3        d1914a2.pssm
4        d1a04a1.pssm
             ...
14225    g2a73.1.pssm
14226    g2dg5.1.pssm
14227    g2vt1.1.pssm
14228    g3bzy.1.pssm
14229    g3n55.1.pssm
Name: pssm_short_names, Length: 14230, dtype: object

In [ ]:
df.iloc[:,0]

0        d12asa_.pssm
1        d16vpa_.pssm
2        d1914a1.pssm
3        d1914a2.pssm
4        d1a04a1.pssm
             ...
14225    g2a73.1.pssm
14226    g2dg5.1.pssm
14227    g2vt1.1.pssm
14228    g3bzy.1.pssm
14229    g3n55.1.pssm
Name: 0, Length: 14230, dtype: object

In [ ]:
res= df2.iloc[:,1].equals(df.iloc[:,0])
print(res)

False

In [ ]:
index_not_matched=[]
for i in range(14230):
  if(df2.iloc[i,1] != df.iloc[i,0]):
    index_not_matched.append(i)

In [ ]:
print(df2.iloc[4402,1])
print(df.iloc[4402,0])

d1ukca_.pssm
nan

In [ ]:
index_not_matched

[4402]

In [ ]:
%cd /content/drive/MyDrive/Project/Features_PSSM/

/content/drive/MyDrive/Project/Features_PSSM

In [ ]:
df1=pd.read_csv('DPC_PSSM.csv')
df2=pd.read_csv('AATP_TPCC.csv')
df3=pd.read_csv('EDP_MEDP.csv')
df4=pd.read_csv('TRIGRAME_PSSM.csv')
df5=pd.read_csv('CS_PSE_PSSM.csv')
df6=pd.read_csv('MBMGAC_PSSM.csv')

df1= df1.drop(columns=['class'], axis=1)
df2= df2.drop(columns=['class'], axis=1)
df3= df3.drop(columns=['class'], axis=1)
df4= df4.drop(columns=['class'], axis=1)
df5= df5.drop(columns=['class'], axis=1)

df7 = pd.concat([df1,df2,df3,df4,df5,df6], axis=1)
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13035 entries, 0 to 13034
Columns: 10501 entries, V1 to class
dtypes: float64(10500), object(1)
memory usage: 1.0+ GB

In [ ]:
df7.tail()

           V1      V2      V3  ...        V559        V560  class
13030  0.3654  0.5481  0.1346  ...    9073.175    9461.005      b
13031  1.1848  1.5638  1.4769  ...  287647.980  303895.461      d
13032 -1.1078  0.8627  0.8627  ...    8159.080    8141.003      d
13033 -1.3900  0.6900  0.4500  ...    7769.568    7952.767      d
13034  0.2966  0.6949  0.7288  ...   12025.509   11144.905      b

[5 rows x 10501 columns]

In [ ]:
df7.to_csv('combined_pssm.csv', index=False)

In [ ]:
df1=pd.read_csv('DPC_PSSM.csv')
df2=pd.read_csv('AATP_TPCC.csv')
df3=pd.read_csv('EDP_MEDP.csv')
df4=pd.read_csv('CS_PSE_PSSM.csv')
df5=pd.read_csv('MBMGAC_PSSM.csv')

df1= df1.drop(columns=['class'], axis=1)
df2= df2.drop(columns=['class'], axis=1)
df3= df3.drop(columns=['class'], axis=1)
df4= df4.drop(columns=['class'], axis=1)

df6 = pd.concat([df1,df2,df3,df4,df5], axis=1)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13035 entries, 0 to 13034
Columns: 2501 entries, V1 to class
dtypes: float64(2500), object(1)
memory usage: 248.7+ MB

In [ ]:
df6.tail()

           V1      V2      V3  ...        V559        V560  class
13030  0.3654  0.5481  0.1346  ...    9073.175    9461.005      b
13031  1.1848  1.5638  1.4769  ...  287647.980  303895.461      d
13032 -1.1078  0.8627  0.8627  ...    8159.080    8141.003      d
13033 -1.3900  0.6900  0.4500  ...    7769.568    7952.767      d
13034  0.2966  0.6949  0.7288  ...   12025.509   11144.905      b

[5 rows x 2501 columns]

In [ ]:
df6.to_csv('combined_pssm2.csv', index=False)

In [ ]:
%cd /content/drive/MyDrive/Project/PSSM Features

/content/drive/.shortcut-targets-by-id/1h10rNk1ZqAojpl6hDsas-ooVdWgH6mg6/PSSM Features

In [ ]:
df1=pd.read_csv('DPC_PSSM.csv', header=None)
df1.tail()

,0,1,2,3,4,5,6,7,8,9,...,411,412,413,414,415,416,417,418,419,420
14225,g2a73.1.pssm,0.3674,0.2779,0.3557,0.3244,0.1861,0.3801,0.3879,0.2236,0.2174,...,0.1283,0.1313,0.1480,0.0792,0.0797,0.1589,0.1514,0.0468,0.0769,0.1462
14226,g2dg5.1.pssm,0.3721,0.2735,0.2839,0.2733,0.0858,0.2792,0.2802,0.2554,0.2495,...,0.0798,0.0681,0.0836,0.0673,0.0478,0.0883,0.0821,0.0416,0.0644,0.0859
14227,g2vt1.1.pssm,0.3916,0.3263,0.2493,0.2606,0.1153,0.3842,0.3706,0.1720,0.3102,...,0.1093,0.0954,0.1428,0.0828,0.0684,0.1098,0.0962,0.0375,0.0839,0.1288
14228,g3bzy.1.pssm,0.3758,0.3199,0.2672,0.2660,0.1134,0.3669,0.3683,0.1800,0.3157,...,0.1073,0.1016,0.1202,0.0765,0.0703,0.1017,0.0905,0.0363,0.0732,0.1242
14229,g3n55.1.pssm,0.3606,0.2402,0.3597,0.2917,0.1764,0.3658,0.3501,0.2420,0.2353,...,0.1487,0.1161,0.1606,0.0980,0.0761,0.1733,0.1958,0.0428,0.0860,0.1803

In [ ]:
pdb=df1[[0]]
pdb.tail()

                  0
14225  g2a73.1.pssm
14226  g2dg5.1.pssm
14227  g2vt1.1.pssm
14228  g3bzy.1.pssm
14229  g3n55.1.pssm

In [ ]:
pdb = pdb[0].str.split('.pssm', n=1, expand=True) 
pdb.tail()

             0 1
14225  g2a73.1
14226  g2dg5.1
14227  g2vt1.1
14228  g3bzy.1
14229  g3n55.1

In [ ]:
pdb=pdb.drop(pdb.columns[1],axis=1)
pdb.tail()

             0
14225  g2a73.1
14226  g2dg5.1
14227  g2vt1.1
14228  g3bzy.1
14229  g3n55.1

In [ ]:
pdb.to_csv('/content/drive/MyDrive/Project/Features_PSSM/pdb.csv', index=False)

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/combined_pssm2.csv")
df.tail()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
13030,0.3654,0.5481,0.1346,0.5385,1.2212,0.1635,0.1442,0.6058,0.5577,0.9712,...,9915.719,9176.061,10704.678,11398.771,10360.027,11108.060,11440.514,9073.175,9461.005,b
13031,1.1848,1.5638,1.4769,2.9390,3.4769,2.3142,2.5730,1.2902,1.6839,3.4455,...,262958.914,285735.507,307587.675,299389.564,316437.921,294029.876,288840.762,287647.980,303895.461,d
13032,-1.1078,0.8627,0.8627,1.2255,1.7255,0.2451,1.0294,0.6765,0.3824,0.9706,...,10471.817,8660.796,10948.821,11523.082,11647.923,9441.705,9310.609,8159.080,8141.003,d
13033,-1.3900,0.6900,0.4500,1.4400,1.7000,0.5700,0.8200,0.8800,0.3700,1.9300,...,10565.884,8806.434,10773.072,10456.661,11102.445,8963.299,8891.549,7769.568,7952.767,d
13034,0.2966,0.6949,0.7288,0.8136,0.9492,0.4237,0.5000,1.5000,1.0508,0.0254,...,12158.411,14458.614,16017.375,15627.743,14401.645,13713.625,13803.527,12025.509,11144.905,b

In [ ]:
df2=pd.concat([pdb,df],axis=1)
df2.head()

,0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
0,d12asa_,0.9877,0.7669,0.7147,0.7791,2.3712,0.4663,0.5644,1.5337,1.0644,...,114070.624,108091.136,114669.085,99283.599,108429.814,99375.890,94187.106,96137.087,101893.312,d
1,d16vpa_,0.1183,0.4592,0.4479,0.5577,0.4423,0.2789,0.3775,0.6761,0.6141,...,137325.433,131197.669,135505.009,117565.612,127873.474,123841.017,118688.798,118811.827,133332.085,d
2,d1914a1,0.6753,0.9351,1.0390,1.8442,0.5844,0.8182,1.0649,1.6623,0.9870,...,5949.595,5316.943,5636.386,5225.542,6527.143,5140.157,5661.591,5220.387,4293.378,d
3,d1914a2,-0.0625,0.4167,0.7083,0.6771,0.5104,0.1042,0.3021,0.2708,0.9688,...,8391.055,8743.541,7549.078,9642.123,9897.976,8942.383,9205.542,9950.298,7470.748,d
4,d1a04a1,2.0909,4.2576,4.5606,5.7576,4.9848,3.6364,4.7273,4.2121,5.4242,...,4683.468,4057.229,4114.765,3349.771,4024.599,4237.269,3284.416,3987.280,3333.758,a

In [ ]:
df2.tail()

,0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
14225,g2a73.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14226,g2dg5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14227,g2vt1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14228,g3bzy.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14229,g3n55.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df3 = df2.rename(columns={0: 'id'})
df3.tail()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
14225,g2a73.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14226,g2dg5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14227,g2vt1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14228,g3bzy.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14229,g3n55.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df4 = df3.iloc[:13035,:]
df4.tail()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
13030,d4ogga1,0.3654,0.5481,0.1346,0.5385,1.2212,0.1635,0.1442,0.6058,0.5577,...,9915.719,9176.061,10704.678,11398.771,10360.027,11108.060,11440.514,9073.175,9461.005,b
13031,d4ogqa_,1.1848,1.5638,1.4769,2.9390,3.4769,2.3142,2.5730,1.2902,1.6839,...,262958.914,285735.507,307587.675,299389.564,316437.921,294029.876,288840.762,287647.980,303895.461,d
13032,d4ogqb_,-1.1078,0.8627,0.8627,1.2255,1.7255,0.2451,1.0294,0.6765,0.3824,...,10471.817,8660.796,10948.821,11523.082,11647.923,9441.705,9310.609,8159.080,8141.003,d
13033,d4ogqh_,-1.3900,0.6900,0.4500,1.4400,1.7000,0.5700,0.8200,0.8800,0.3700,...,10565.884,8806.434,10773.072,10456.661,11102.445,8963.299,8891.549,7769.568,7952.767,d
13034,d4oh3a_,0.2966,0.6949,0.7288,0.8136,0.9492,0.4237,0.5000,1.5000,1.0508,...,12158.411,14458.614,16017.375,15627.743,14401.645,13713.625,13803.527,12025.509,11144.905,b

In [ ]:
df4.to_csv('/content/drive/MyDrive/Project/Features_PSSM/data.csv', index=False)

#code for flask

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Project/Features_PSSM/data.csv")
df.tail()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
13030,d4ogga1,0.3654,0.5481,0.1346,0.5385,1.2212,0.1635,0.1442,0.6058,0.5577,...,9915.719,9176.061,10704.678,11398.771,10360.027,11108.060,11440.514,9073.175,9461.005,b
13031,d4ogqa_,1.1848,1.5638,1.4769,2.9390,3.4769,2.3142,2.5730,1.2902,1.6839,...,262958.914,285735.507,307587.675,299389.564,316437.921,294029.876,288840.762,287647.980,303895.461,d
13032,d4ogqb_,-1.1078,0.8627,0.8627,1.2255,1.7255,0.2451,1.0294,0.6765,0.3824,...,10471.817,8660.796,10948.821,11523.082,11647.923,9441.705,9310.609,8159.080,8141.003,d
13033,d4ogqh_,-1.3900,0.6900,0.4500,1.4400,1.7000,0.5700,0.8200,0.8800,0.3700,...,10565.884,8806.434,10773.072,10456.661,11102.445,8963.299,8891.549,7769.568,7952.767,d
13034,d4oh3a_,0.2966,0.6949,0.7288,0.8136,0.9492,0.4237,0.5000,1.5000,1.0508,...,12158.411,14458.614,16017.375,15627.743,14401.645,13713.625,13803.527,12025.509,11144.905,b

In [ ]:
df.iloc[13034,0]

'd4oh3a_'

In [ ]:
type(df.iloc[0,1:-1].values)

numpy.ndarray

In [ ]:
import pickle

In [ ]:
!pip install -U xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Collecting xgboost
  Downloading xgboost-1.5.2-py3-none-manylinux2014_x86_64.whl (173.6 MB)
     |████████████████████████████████| 173.6 MB 8.1 kB/s
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.21.5)
Installing collected packages: xgboost
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
Successfully installed xgboost-1.5.2

In [ ]:
model = pickle.load(open("/content/drive/MyDrive/Project/Features_PSSM/model.dat","rb"))

In [ ]:
index=-1
def predict(pdb):
  for i in range(0,13035):
    if(pdb==df.iloc[i,0]):
      index=i
      print(index)
      tmp=df.iloc[index,1:-1]
      result=pd.DataFrame([tmp])
      return model.predict(result)
  return -1

In [ ]:
tmp=predict("d4ogqb_")
print(tmp)
print(type(tmp))

13032
[3]
<class 'numpy.ndarray'>

In [ ]:

tmp=predict("d4oh3a_")
print(tmp)
print(type(tmp))

13034
[1]
<class 'numpy.ndarray'>

In [ ]:
predict("aass")

-1

In [ ]:

tmp=predict("d1a04a1")
print(tmp)
print(type(tmp))

4
[0]
<class 'numpy.ndarray'>

In [ ]:
df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V552,V553,V554,V555,V556,V557,V558,V559,V560,class
0,d12asa_,0.9877,0.7669,0.7147,0.7791,2.3712,0.4663,0.5644,1.5337,1.0644,...,114070.624,108091.136,114669.085,99283.599,108429.814,99375.890,94187.106,96137.087,101893.312,d
1,d16vpa_,0.1183,0.4592,0.4479,0.5577,0.4423,0.2789,0.3775,0.6761,0.6141,...,137325.433,131197.669,135505.009,117565.612,127873.474,123841.017,118688.798,118811.827,133332.085,d
2,d1914a1,0.6753,0.9351,1.0390,1.8442,0.5844,0.8182,1.0649,1.6623,0.9870,...,5949.595,5316.943,5636.386,5225.542,6527.143,5140.157,5661.591,5220.387,4293.378,d
3,d1914a2,-0.0625,0.4167,0.7083,0.6771,0.5104,0.1042,0.3021,0.2708,0.9688,...,8391.055,8743.541,7549.078,9642.123,9897.976,8942.383,9205.542,9950.298,7470.748,d
4,d1a04a1,2.0909,4.2576,4.5606,5.7576,4.9848,3.6364,4.7273,4.2121,5.4242,...,4683.468,4057.229,4114.765,3349.771,4024.599,4237.269,3284.416,3987.280,3333.758,a